name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: 'API URL for the application'
        required: true
        default: 'https://fiddle.clickhouse.com/api/'
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker tags
        id: tags
        run: |
          echo "::set-output name=tags::lodthe/clickhouse-playground-ui:${{ github.event.inputs.tag }}"
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            API_URL=${{ github.event.inputs.api_url }}
          cache-from: type=gha
          cache-to: type=gha,mode=max